# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/p500/setup-makefiles.sh


# -------------------------------------------------------------------
# PREBUILT LIBRARIES THAT ARE NEEDED TO BUILD OPEN-SOURCE LIBRARIES -
# -------------------------------------------------------------------
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
######################    DEPENDENCY SECTION  #######################
PRODUCT_COPY_FILES += \
    vendor/lge/p500/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/lge/p500/proprietary/lib/libmmipl.so:obj/lib/libmmipl.so \
    vendor/lge/p500/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so \
    vendor/lge/p500/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/lge/p500/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so


#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
###################### DON'T EDIT ###################################
PRODUCT_COPY_FILES += \
    vendor/lge/gt540/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/gt540/proprietary/etc/flex/flex.xml:system/etc/flex/flex.xml \
    vendor/lge/gt540/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/lge/gt540/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/gt540/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/lge/gt540/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/lge/gt540/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/gt540/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/gt540/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/gt540/proprietary/lib/libril_log.so:system/lib/libril_log.so \
    vendor/lge/gt540/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/gt540/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/lge/gt540/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/gt540/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/lge/gt540/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/gt540/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/lge/gt540/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/lge/gt540/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/lge/gt540/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
    vendor/lge/gt540/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/lge/gt540/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/lge/gt540/proprietary/lib/liblgerft.so:system/lib/liblgerft.so \
    vendor/lge/gt540/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/lge/gt540/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/lge/gt540/proprietary/lib/libbcmwl.so:system/lib/libbcmwl.so \
    vendor/lge/gt540/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/lge/gt540/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/gt540/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/gt540/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/gt540/proprietary/lib/libsnd.so:system/lib/libsnd.so \
    vendor/lge/gt540/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/lge/gt540/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/gt540/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/lge/gt540/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/gt540/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/gt540/proprietary/bin/BCM4325D1_004.002.004.0262.0270.hcd:system/bin/BCM4325D1_004.002.004.0262.0270.hcd \
    vendor/lge/gt540/proprietary/etc/wl/rtecdc.bin:system/etc/wl/rtecdc.bin \
    vendor/lge/gt540/proprietary/etc/wl/rtecdc-apsta.bin:system/etc/wl/rtecdc-apsta.bin \
    vendor/lge/gt540/proprietary/etc/wl/rtecdc-mfgtest.bin:system/etc/wl/rtecdc-mfgtest.bin \
    vendor/lge/gt540/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/lge/gt540/proprietary/lib/hw/sensors.msm7x27.so:system/lib/hw/sensors.msm7x27.so
